### PR TITLE
Adapted probabilities (starting cost + BOS/EOS)

### PR DESCRIPTION
**Pull request by pauloamed**
Now sequences also have a starting probability (using the `disconnect` transition). Also, `BOS` and `EOS` tags were implemented for handling border cases. Some code duplication was tackled during implementation.

### CODE REVIEW

**Comment by pauloamed** [comment]
#93

**Comment by pauloamed** [comment]
Closes #93

**Comment by pauloamed** [comment]
Found some errors, will push again later.

**Comment by pauloamed** [comment]
`BOS` and `EOS` won't compose any phrase. Thus, their `connect` probabilities will be, by def., 0. This implies that their `disconnect` costs will always be 1, regardless of what comes after/before. It seems that using these tags is unpractical in this modelling. 

However, capturing the starting cost still seems possible. Starting a phrase in the `i-th` token should account `disconnect[tags[i-1]][tags[i]]`. 
We still need to define the cost of starting a phrase with `tags[0]`. If it is `prob=1`, we are favoring these over phrases that start middle-sentence. I don't know, though, if this favoring is really significant.

**Comment by remenberl** [comment]
How do we handle the cost of ending a phrase with tags[n]? I don't remember the details. But is the situation you described for starting has already been the case for the phrase ending? That is, the cost of ending a phrase with tags[n] is 1.

**Comment by pauloamed** [comment]
You are right. I was struggling to realize that this initial cost will affect any phrase, regardless of it starting the sentence. Thanks, Jialu. I will open another PR.

**Comment by pauloamed** [comment]
This starting cost is utterly wrong. Now I see why. The cost of ending isn't actually `ending`, but segmenting. This cost is already being considered in `f[i]` when trying to segment `[i;j]`. Sorry for not noticing it before.

**Pull request closed without merging**
